#!/usr/bin/env python3
"""
Neuroscience Daily Digest - Word文档生成器（标准版）
格式特征：
- 标题：英文斜体，14pt，黑色
- 来源：灰色小字
- 英文摘要：标题"Abstract (English)"深蓝色，内容10.5pt
- 中文摘要：标题"中文摘要"深红色，内容10.5pt
- 分隔线：灰色虚线
"""

from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

# 默认配色方案
COLORS = {
    'title': (0, 0, 0),           # 黑色
    'source': (80, 80, 80),       # 灰色
    'eng_header': (0, 51, 102),   # 深蓝色
    'cn_header': (139, 0, 0),     # 深红色
    'text': (0, 0, 0),            # 黑色
    'separator': (200, 200, 200), # 浅灰
    'footer': (150, 150, 150),    # 灰色
}

def create_word_document(articles, output_path, date_str=None):
    """
    创建Word文档
    
    Args:
        articles: 文章列表，每篇包含 title, source, date, abstract, translated
        output_path: 输出文件路径
        date_str: 日期字符串，默认使用当天
    """
    if date_str is None:
        date_str = datetime.now().strftime('%Y-%m-%d')
    
    doc = Document()
    
    # 设置默认字体
    style = doc.styles['Normal']
    style.font.name = 'Times New Roman'
    style._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
    style.font.size = Pt(11)
    
    # 主标题
    title = doc.add_heading(f'Neuroscience Daily Digest | {date_str}', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.runs[0]
    title_run.font.size = Pt(18)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0, 0, 128)
    title_run.font.name = 'Times New Roman'
    title_run._element.rPr.rFonts.set(qn('w:eastAsia'), '微软雅黑')
    
    # 副标题
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle.add_run(f'今日精选 {len(articles)} 篇神经科学前沿文献')
    subtitle_run.font.size = Pt(12)
    subtitle_run.font.italic = True
    subtitle_run.font.color.rgb = RGBColor(100, 100, 100)
    subtitle_run.font.name = 'Times New Roman'
    subtitle_run._element.rPr.rFonts.set(qn('w:eastAsia'), '微软雅黑')
    
    doc.add_paragraph()  # 空行
    
    # 添加每篇文章
    for i, article in enumerate(articles, 1):
        # 文章序号和标题（斜体）
        heading = doc.add_heading(level=1)
        heading_run = heading.add_run(f"{i}. {article['title']}")
        heading_run.font.size = Pt(14)
        heading_run.font.italic = True
        heading_run.font.color.rgb = RGBColor(*COLORS['title'])
        heading_run.font.name = 'Times New Roman'
        
        # 来源和日期
        source_para = doc.add_paragraph()
        source_run = source_para.add_run(f"Source: {article['source']} | {article['date']}")
        source_run.font.size = Pt(10)
        source_run.font.color.rgb = RGBColor(*COLORS['source'])
        source_run.font.name = 'Times New Roman'
        source_para.paragraph_format.space_after = Pt(6)
        
        # 英文摘要标题
        eng_title = doc.add_paragraph()
        eng_title_run = eng_title.add_run("Abstract (English)")
        eng_title_run.font.size = Pt(11)
        eng_title_run.font.bold = True
        eng_title_run.font.color.rgb = RGBColor(*COLORS['eng_header'])
        eng_title_run.font.name = 'Times New Roman'
        
        # 英文摘要内容
        eng_abstract = doc.add_paragraph()
        eng_abstract_run = eng_abstract.add_run(article.get('abstract', ''))
        eng_abstract_run.font.size = Pt(10.5)
        eng_abstract.paragraph_format.line_spacing = 1.15
        eng_abstract.paragraph_format.space_after = Pt(8)
        
        # 中文摘要标题
        cn_title = doc.add_paragraph()
        cn_title_run = cn_title.add_run("中文摘要")
        cn_title_run.font.size = Pt(11)
        cn_title_run.font.bold = True
        cn_title_run.font.color.rgb = RGBColor(*COLORS['cn_header'])
        cn_title_run.font.name = 'Times New Roman'
        cn_title_run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        
        # 中文摘要内容
        cn_abstract = doc.add_paragraph()
        cn_abstract_run = cn_abstract.add_run(article.get('translated', ''))
        cn_abstract_run.font.size = Pt(10.5)
        cn_abstract_run.font.name = 'Times New Roman'
        cn_abstract_run._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
        cn_abstract.paragraph_format.line_spacing = 1.15
        cn_abstract.paragraph_format.space_after = Pt(12)
        
        # 分隔线
        if i < len(articles):
            separator = doc.add_paragraph()
            separator_run = separator.add_run("─" * 60)
            separator_run.font.color.rgb = RGBColor(*COLORS['separator'])
            separator.alignment = WD_ALIGN_PARAGRAPH.CENTER
            separator.paragraph_format.space_before = Pt(6)
            separator.paragraph_format.space_after = Pt(12)
    
    # 页脚
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run(f"Generated by Neuroscience Daily Digest System | {date_str}")
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(*COLORS['footer'])
    footer_run.font.italic = True
    footer_run.font.name = 'Times New Roman'
    
    # 保存文档
    doc.save(output_path)
    print(f"✅ Word文档已保存: {output_path}")
    return output_path


def parse_articles_from_md(md_content):
    """从Markdown解析文章列表"""
    import re
    
    articles = []
    lines = md_content.split('\n')
    current = {}
    
    for line in lines:
        line = line.strip()
        
        # 匹配标题行: ### 1. Title
        if line.startswith('### ') and '. ' in line:
            if current and 'title' in current:
                articles.append(current)
            current = {}
            parts = line.replace('### ', '').split('. ', 1)
            current['number'] = parts[0]
            current['title'] = parts[1]
        
        # 匹配来源行
        elif line.startswith('📄') and '|' in line:
            parts = line.replace('📄 *', '').strip('*').split(' | ')
            if len(parts) == 2:
                current['source'] = parts[0]
                current['date'] = parts[1]
        
        # 匹配摘要
        elif line.startswith('**摘要**：'):
            current['abstract'] = line.replace('**摘要**：', '')
        
        # 匹配中文翻译（括号内的内容）
        elif line.startswith('*') and line.endswith('*') and 'title' in current:
            current['translated'] = line.strip('*')
    
    if current and 'title' in current:
        articles.append(current)
    
    return articles


def main():
    """命令行入口"""
    import sys
    
    if len(sys.argv) < 3:
        print("用法: python generate_word.py --input input.md --output output.docx")
        return
    
    input_file = sys.argv[2]
    output_file = sys.argv[4] if len(sys.argv) > 4 else 'Neuroscience_Daily_Digest.docx'
    
    # 读取Markdown
    with open(input_file, 'r', encoding='utf-8') as f:
        md_content = f.read()
    
    # 解析文章
    articles = parse_articles_from_md(md_content)
    
    if not articles:
        print("⚠️ 未找到文章，请检查Markdown格式")
        return
    
    # 生成Word
    create_word_document(articles, output_file)
    print(f"共处理 {len(articles)} 篇文章")


if __name__ == "__main__":
    main()
